wandb_version: 1

batch_size:
  value: 50
dropout:
  value: 0
epoch:
  value: 10
gamma:
  value: 1
learning_rate:
  value: 0.01
loss:
  value: customLoss-8
model:
  value: cnn
optimizer:
  value: adam
