wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1678718238.398144
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value:
    values:
    - 50
dropout:
  desc: null
  value:
    values:
    - 0
epoch:
  desc: null
  value:
    values:
    - 10
gamma:
  desc: null
  value:
    values:
    - 1
learning_rate:
  desc: null
  value:
    values:
    - 0.01
optimizer:
  desc: null
  value:
    values:
    - adam
