wandb_version: 1

batch_size:
  value: 50
dropout:
  value: 0
epoch:
  value: 20
exponent:
  value: 1
gamma:
  value: 1
learning_rate:
  value: 0.01
loss:
  value: customLoss
model:
  value: cnn
optimizer:
  value: adam
