wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.16
    start_time: 1677101776.16289
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 1
      - 2
      - 13
      - 16
      - 23
      4: 3.9.16
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
epochs:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.02
